language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Podfile
notifications:
  slack: kumapo:ydUxkFOe2m4wlNH7Lw3ZesoE
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- xcodebuild -workspace RxSwiftTestSchedulerExample.xcworkspace -scheme RxSwiftTestSchedulerExampleTests -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' test
