language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Podfile
notifications:
  slack: kumapo:ydUxkFOe2m4wlNH7Lw3ZesoE
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -workspace RxSwiftTestSchedulerExample.xcworkspace -scheme RxSwiftTestSchedulerExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild test -workspace RxSwiftTestSchedulerExample.xcworkspace -scheme RxSwiftTestSchedulerExampleTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
